apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kmcvg6x43-nodejs-gitops
  description: This is GitOps manifest for kmcvg6x43-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: kmcvg6x43-nodejs
    janus-idp.io/tekton: kmcvg6x43-nodejs 
    backstage.io/kubernetes-id: kmcvg6x43-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kmcvg6x43-nodejs
