apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kmcvg6x43-nodejs
  janus-idp.io/tekton: kmcvg6x43-nodejs
  backstage.io/kubernetes-id: kmcvg6x43-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kmcvg6x43-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
